services:
  backend:
    build: .
    container_name: quiz_game_backend
    restart: always
    ports:
      - "127.0.0.1:8081:81"
    environment:
      - TZ=Asia/Tehran
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin_username}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin_password}
    # command پاک شد تا از دستور پیش‌فرض Dockerfile استفاده شود
    # volumes پاک شد تا کانتینر از کدهای کپی شده داخل ایمیج استفاده کند
