services:
  backend:
    build: .
    container_name: quiz_game_backend
    ports:
      - "8081:81"
    volumes:
      - ./app:/code/app
      - ./tests:/code/tests
    environment:
      - TZ=Asia/Tehran
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin_username}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin_password}
    command: uvicorn app.main:app --host 0.0.0.0 --port 81 --reload